import type { Metadata } from 'next';
import { Inter, Fira_Code } from 'next/font/google';
import '../styles/globals.css';

const inter = Inter({
    variable: '--font-sans',
    subsets: ['latin'],
});

const firaCode = Fira_Code({
    variable: '--font-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${firaCode.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
